export const GET_SOOTBLOW_DATA_REQUEST = 'GET_SOOTBLOW_DATA_REQUEST';
export const GET_SOOTBLOW_DATA_SUCCESS = 'GET_SOOTBLOW_DATA_SUCCESS';
export const GET_SOOTBLOW_DATA_FAILED = 'GET_SOOTBLOW_DATA_FAILED';
