export const GET_PARAMETER_TABLE_REQUEST = 'GET_PARAMETER_TABLE_REQUEST';
export const GET_PARAMETER_TABLE_SUCCESS = 'GET_PARAMETER_TABLE_SUCCESS';
export const GET_PARAMETER_TABLE_FAILED = 'GET_PARAMETER_TABLE_FAILED';
