export const GET_COMBUSTION_TIMESTAMP_REQUEST = 'GET_COMBUSTION_TIMESTAMP_REQUEST';
export const GET_COMBUSTION_TIMESTAMP_SUCCESS = 'GET_COMBUSTION_TIMESTAMP_SUCCESS';
export const GET_COMBUSTION_TIMESTAMP_FAILED = 'GET_COMBUSTION_TIMESTAMP_FAILED';

export const GET_COMBUSTION_CONSTRAINTS_REQUEST = 'GET_COMBUSTION_CONSTRAINTS_REQUEST';
export const GET_COMBUSTION_CONSTRAINTS_SUCCESS = 'GET_COMBUSTION_CONSTRAINTS_SUCCESS';
export const GET_COMBUSTION_CONSTRAINTS_FAILED = 'GET_COMBUSTION_CONSTRAINTS_FAILED';
